# Generated by Django 5.1.7 on 2025-03-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('cambio', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=30)),
                ('combustivel', models.CharField(max_length=20)),
            ],
        ),
    ]
